import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Icon from '@/components/Icon';
import { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [name, setName] = useState('FaAppStoreIos');
  const [size, setSize] = useState('48px');
  const [color, setColor] = useState('royalblue');

  return (
    <>
      <Head>
        <title>Icons on Demand Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <h1>Hello World!</h1>

        <Icon name="FaAdn" />
        <Icon name="FaAirbnb" color="red" />
        <Icon name="FaAdn" size="24px" color="royalblue" />
        <Icon name="FaAlgolia" />

        <h2>Icon Test</h2>
        <p>
          Use icons from{' '}
          <a href="https://react-icons.github.io/react-icons">react-icons</a>{' '}
          specificaly from FontAwesome
        </p>

        <input
          type="input"
          value={name}
          placeholder="Icon Name"
          onChange={e => setName(e.target.value)}
        />
        <input
          type="input"
          value={size}
          placeholder="Icon Size (with px, em, etc suffix)"
          onChange={e => setSize(e.target.value)}
        />
        <input
          type="input"
          value={color}
          placeholder="Icon Color"
          onChange={e => setColor(e.target.value)}
        />

        <div>
          <h3>Icon: </h3>
          <Icon name={name} size={size} color={color} />
        </div>
      </main>
    </>
  );
}
